apps/cart/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import CartAddView,CartInfoView,CartUpdateView,CartDeleteView

app_name='cart'
urlpatterns = [
    path('add/', CartAddView.as_view(),name='add'),
    path('update/',CartUpdateView.as_view(),name='update'),
    path('delete/',CartDeleteView.as_view(),name='delete'),
    path('',CartInfoView.as_view(),name='show')
]

apps/goods/urls.py
from django.urls import path
from .views import IndexView, DetailView, ListView

app_name = 'goods'
urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    path('goods/<int:goods_id>', DetailView.as_view(), name='detail'),
    path('list/<int:type_id>/<int:page>', ListView.as_view(), name='list'),
    # path('', IndexView.as_view(), name='index')
]

apps/user/urls.py
from django.urls import path
from .views import name_check, email_check, RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, \
    UserOrderView, AddressView, set_default_addr
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='user/password_reset_form.html',
        email_template_name='user/password_reset_email.html',
        success_url='/user/password-reset-done/'),
         name="password_reset"),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'),
         name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html",
                                                     success_url='/user/password-reset-complete/'),
         name="password_reset_confirm"),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name="user/password_change_form.html",
                                                                   success_url="/user/password-change-done/"),
         name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name="user/password_change_done.html"),
         name='password_change_done'),
    path('name_check/', name_check, name='name_check'),
    path('email_check/', email_check, name='email_check'),
    path('register/', RegisterView.as_view(), name='register'),
    path('active/<str:token>', ActiveView.as_view(), name='active'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('order/<int:page>', UserOrderView.as_view(), name='order'),
    path('address/', csrf_exempt(AddressView.as_view()), name='address'),
    path('setdef/', set_default_addr, name='setdef'),
    path('', UserInfoView.as_view(), name='user'),

]

leyton_mall/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    path('search/',include('haystack.urls')),
    path('user/', include('apps.user.urls' ,namespace='user')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('', include('apps.goods.urls', namespace='goods')),
]

templates/base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容快 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
    {# 网页顶部欢迎信息块 #}
    {% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到雷顿商城!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% endblock header_con %}

    {# 网页搜索框块 #}
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search/">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>

        {% block cart_bar %}
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			{% if cart_count %}
			    <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
            {% else %}
                <div class="goods_count fl" id="show_count">0</div>
            {% endif %}
        </div>
        {% endblock cart_bar %}

	</div>
    {% endblock search_bar %}

	{# 网页主体内容块 #}
    {% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="https://github.com/LeytonYu">联系作者</a>
			<span>|</span>
			<a href="https://github.com/LeytonYu">GitHub</a>
		</div>
		<p>CopyRight © 2020 杭州雷顿信息技术有限公司 All Rights Reserved</p>
		<p>电话：15857590552    <a href="http://www.beian.miit.gov.cn">浙ICP备19042933号-1</a> </p>
	</div>

    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}

    {# 网页底部引入文件块 #}
    {% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{# 网页主体内容块 #}
{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for type in types %}
                        <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机雷顿</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>
    {# 详情页 列表页 主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_no_cart.html
{# 购物车页面 提交订单页面 #}
{% extends 'base.html' %}
{% load static %}
{# 网页搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
            <form action="/search/" method="get">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock search_bar %}

templates/base_user_center.html
{# 用户中心-3个页面 #}
{% extends 'base_no_cart.html' %}
{% block title %}雷顿商城-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}

{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1%}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心-右侧内容块 #}
		{% block right_content %}{% endblock right_content %}
	</div>
{% endblock body %}

templates/static_base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容快 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
    {# 网页顶部欢迎信息块 #}
    {% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到雷顿商城!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% endblock header_con %}

    {# 网页搜索框块 #}
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>

        {% block cart_bar %}
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			{% if cart_count %}
			    <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
            {% else %}
                <div class="goods_count fl" id="show_count">0</div>
            {% endif %}
		</div>
        {% endblock cart_bar %}

	</div>
    {% endblock search_bar %}

	{# 网页主体内容块 #}
    {% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="https://github.com/LeytonYu">关于作者</a>
			<span>|</span>
			<a href="https://github.com/LeytonYu">联系作者</a>
			<span>|</span>
			<a href="#">更快更强</a>
		</div>
		<p>CopyRight © 2020 杭州雷顿信息技术有限公司 All Rights Reserved</p>
		<p>电话：15857590552    <a href="http://www.beian.miit.gov.cn">浙ICP备19042933号-1</a> </p>
	</div>

    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}

    {# 网页底部引入文件块 #}
    {% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/static_index.html
{% extends 'static_base.html' %}
{% load static %}
{% block title %}雷顿商城-首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机雷顿</a></li>
                <li class="interval">|</li>
                <li><a href="https://choujiang.51240.com/">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">
            {% for type in types %}
                <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                {% for banner in goods_banners %}
                    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}"
                                                                              alt="幻灯片"></a></li>
                {% endfor %}
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            {% for banner in promotion_banners %}
                <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
        </div>
    </div>
    {% for type in types %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for banner in type.title_banner %}
                        <a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                    {% endfor %}
                </div>
                <a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
                <ul class="goods_list fl">
                    {% for banner in type.image_banner %}
                        <li>
                            <h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
                            <a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
                            <div class="prize">¥ {{ banner.sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}
{% endblock body %}