apps/goods/urls.py
from django.urls import path
from .views import IndexView, DetailView, ListView

app_name = 'goods'
urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    path('goods/<int:goods_id>', DetailView.as_view(), name='detail'),
    path('list/<int:type_id>/<int:page>', ListView.as_view(), name='list'),
    # path('', IndexView.as_view(), name='index')
]

apps/order/urls.py
from django.urls import path
from .views import OrderPlaceView, OrderCommintView, OrderPayView,OrderCheckView,OrderCommentView

app_name='order'
urlpatterns = [
    path('place/', OrderPlaceView.as_view(),name='place'),
    path('commit/',OrderCommintView.as_view(),name='commit'),
    path('pay/',OrderPayView.as_view(),name='pay'),
    path('check/',OrderCheckView.as_view(),name='check'),
    path('comment/<str:order_id>',OrderCommentView.as_view(),name='comment'),
]

apps/user/urls.py
from django.urls import path
from .views import name_check, email_check, RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, \
    UserOrderView, AddressView, set_default_addr
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='user/password_reset_form.html',
        email_template_name='user/password_reset_email.html',
        success_url='/user/password-reset-done/'),
         name="password_reset"),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'),
         name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html",
                                                     success_url='/user/password-reset-complete/'),
         name="password_reset_confirm"),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name="user/password_change_form.html",
                                                                   success_url="/user/password-change-done/"),
         name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name="user/password_change_done.html"),
         name='password_change_done'),
    path('name_check/', name_check, name='name_check'),
    path('email_check/', email_check, name='email_check'),
    path('register/', RegisterView.as_view(), name='register'),
    path('active/<str:token>', ActiveView.as_view(), name='active'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('order/<int:page>', UserOrderView.as_view(), name='order'),
    path('address/', csrf_exempt(AddressView.as_view()), name='address'),
    path('setdef/', set_default_addr, name='setdef'),
    path('', UserInfoView.as_view(), name='user'),

]

leyton_mall/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    path('search/',include('haystack.urls')),
    path('user/', include('apps.user.urls' ,namespace='user')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('', include('apps.goods.urls', namespace='goods')),
]

apps/goods/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField


# Create your models here.

class GoodsType(BaseModel):
    """商品类型模型类"""
    name = models.CharField(max_length=20, verbose_name='种类名称')
    logo = models.CharField(max_length=20, verbose_name='标识')
    image = models.ImageField(upload_to='type', verbose_name='商品类型图片')

    class Meta:
        db_table = 'lm_goods_type'
        verbose_name = '商品种类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsSKU(BaseModel):
    """商品SKU模型"""
    status_choice = (
        (0, '下线'),
        (1, '上线')
    )   # 后期可以扩充状态
    type = models.ForeignKey('GoodsType', on_delete=models.CASCADE, verbose_name='商品种类')
    goods = models.ForeignKey('Goods', on_delete=models.CASCADE, verbose_name='商品SPU')
    name = models.CharField(max_length=100, verbose_name='商品名称')
    desc = models.CharField(max_length=256, verbose_name='商品简介')
    price = models.DecimalField(max_digits=20, decimal_places=2, verbose_name='价格')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    image = models.ImageField(upload_to='goods', verbose_name='商品图片')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    status = models.SmallIntegerField(default=1, choices=status_choice, verbose_name='状态')
    freight = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='运费')

    class Meta:
        db_table = 'lm_goods_sku'
        verbose_name = '商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Goods(BaseModel):
    """商品SPU模型类"""
    name = models.CharField(max_length=80, verbose_name='商品SPU名称')
    # 富文本类型
    detail = HTMLField(blank=True, verbose_name='商品详情')

    class Meta:
        db_table = 'lm_goods_spu'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsImage(BaseModel):
    sku = models.ForeignKey('GoodsSKU', on_delete=models.CASCADE, verbose_name='商品')
    image = models.ImageField(upload_to='goods', verbose_name='图片路径')

    class Meta:
        db_table = 'lm_goods_image'
        verbose_name = '商品图片'
        verbose_name_plural = verbose_name


class IndexGoodsBanner(BaseModel):
    """首页轮播商品模型类"""
    sku = models.ForeignKey('GoodsSKU', on_delete=models.CASCADE, verbose_name='商品')
    image = models.ImageField(upload_to='banner', verbose_name='图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'lm_index_banner'
        verbose_name = '首页轮播商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.name


class IndexTypeGoodsBanner(BaseModel):
    """首页分类商品展示模型类"""
    DISPLAY_TYPE_CHOICES = (
        (0, '标题'),
        (1, '图片')
    )

    type = models.ForeignKey('GoodsType', on_delete=models.CASCADE, verbose_name='商品类型')
    sku = models.ForeignKey('GoodsSKU', on_delete=models.CASCADE, verbose_name='商品SKU')
    display_type = models.SmallIntegerField(default=1, choices=DISPLAY_TYPE_CHOICES, verbose_name='展示类型')
    index = models.SmallIntegerField(default=1, verbose_name='展示顺序')

    class Meta:
        db_table = 'lm_index_type_goods'
        verbose_name = '主页分类展示商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.name


class IndexPromotionBanner(BaseModel):
    """首页促销活动模型类"""
    name = models.CharField(max_length=20, verbose_name="活动名称")
    url = models.URLField(verbose_name='活动链接')
    image = models.ImageField(upload_to='banner', verbose_name='活动图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'lm_index_promotion'
        verbose_name = "主页促销活动"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/user/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.http import HttpResponse, JsonResponse, QueryDict
from django.views.decorators.csrf import csrf_exempt
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password

from apps.order.models import OrderInfo, OrderGoods
from celery_tasks.tasks import send_register_active_email
import re
from .models import User, Address
from apps.goods.models import GoodsSKU
from django_redis import get_redis_connection
from django.db.models import Q


# Create your views here.

# /user/name_check
@csrf_exempt
def name_check(request):
    """注册校验用户名是否重复"""
    if len(User.objects.filter(username=request.POST.get('name'))) == 0:
        return JsonResponse({'resultCode': 0})  # 没重复
    return JsonResponse({'resultCode': 1})


# /user/email_check
@csrf_exempt
def email_check(request):
    if len(User.objects.filter(email=request.POST.get('email'))) == 0:
        return JsonResponse({'resultCode': 0})  # 没重复
    return JsonResponse({'resultCode': 1})


# /user/register
class RegisterView(View):
    """注册"""

    def get(self, request):
        """显示注册页"""
        return render(request, 'user/register.html')

    def post(self, request):
        """经行注册处理"""
        print("提交注册请求")
        username = request.POST.get('user_name')
        password = request.POST.get('pwd')
        email = request.POST.get('email')
        allow = request.POST.get('allow')

        if not all([username, password, email]):
            return render(request, 'user/register.html', {'errmsg': '数据不完整'})

        if not re.match('^.+\\@(\\[?)[a-zA-Z0-9\\-\\.]+\\.([a-zA-Z]{2,3}|[0-9]{1,3})(\\]?)$', email):
            return render(request, 'user/register.html', {'errmsg': '邮箱格式不正确'})

        if allow != 'on':
            return render(request, 'user/register.html', {'errmsg': '请同意协议'})
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = None
        if user:
            return render(request, 'user/register.html', {'errmsg': '用户名已存在'})
        # 用户注册数据库操作
        user = User.objects.create_user(username, email, password)
        user.is_active = 0
        user.save()
        #  加密用户信息
        serializer = Serializer(settings.SECRET_KEY, 3600)
        info = {'confirm': user.id}
        token = serializer.dumps(info)
        token = token.decode()

        print('发邮件前')
        # celery异步发邮件
        send_register_active_email.delay(email, username, token)
        print('委托发邮件后')
        return redirect(reverse('goods:index'))


# /user/active/token
class ActiveView(View):
    """用户激活"""

    def get(self, request, token):
        """用户激活"""
        serializer = Serializer(settings.SECRET_KEY, 3600)
        try:
            info = serializer.loads(token)
            user_id = info['confirm']
            user = User.objects.get(id=user_id)
            user.is_active = 1
            user.save()
            return redirect(reverse('user:login'))
        except SignatureExpired as e:
            return HttpResponse('激活链接已过期')


# /user/login
class LoginView(View):
    """登录"""

    def get(self, request):
        """显示登录页面"""

        if 'username' in request.COOKIES:
            username = request.COOKIES.get('username')
            checked = 'checked'
        else:
            username = ''
            checked = ''

        return render(request, 'user/login.html', {'username': username, 'checked': checked})

    def post(self, request):
        """登录校验"""
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        print(username, password)
        if not all([username, password]):
            return render(request, 'user/login.html', {'errmsg': '请检查信息完整性'})

        user = User.objects.filter(Q(username=username) | Q(email=username))
        if user:
            user = user[0]
            password2 = user.password
            if check_password(password, password2):
                if user.is_active:
                    login(request, user)
                    next_url = request.GET.get('next', reverse('goods:index'))
                    response = redirect(next_url)
                    remember = request.POST.get('remember')
                    if remember == 'on':
                        response.set_cookie('username', username, max_age=7 * 24 * 3600)
                    else:
                        response.delete_cookie('username')
                    return response
                else:
                    return render(request, 'user/login.html', {'errmsg': '账户未激活'})
            return render(request, 'user/login.html', {'errmsg': '用户名或密码错误'})
        else:
            return render(request, 'user/login.html', {'errmsg': '用户不存在'})


# /user/logout
class LogoutView(View):
    """退出登录"""

    def get(self, request):
        """退出登录"""
        logout(request)

        return redirect(reverse('goods:index'))


# /user
class UserInfoView(LoginRequiredMixin, View):
    """用户中心-信息页"""

    def get(self, request):
        """显示"""
        user = request.user
        address = Address.objects.get_default_address(user)

        con = get_redis_connection('default')
        history_key = 'history_%d' % user.id
        # 获取用户最新浏览的5个商品的id
        sku_ids = con.lrange(history_key, 0, 4)
        goods_list = []
        for id in sku_ids:
            goods = GoodsSKU.objects.get(id=id)
            goods_list.append(goods)

        context = {
            'page': 'user',
            'address': address,
            'goods_list': goods_list
        }

        return render(request, 'user/user_center_info.html', context)


# /user/order
class UserOrderView(LoginRequiredMixin, View):
    """用户中心-订单页"""

    def get(self, request, page):
        user = request.user
        orders = OrderInfo.objects.filter(user=user).order_by('-create_time')

        for order in orders:
            order_goods = OrderGoods.objects.filter(order_id=order.order_id)
            for order_good in order_goods:
                amount = order_good.count * order_good.price
                order_good.amount = amount
            order.status_name = OrderInfo.ORDER_STATUS[order.order_status]
            order.order_goods = order_goods

        paginator = Paginator(orders, 2)
        try:
            page = int(page)
        except Exception:
            page = 1
        num_pages = paginator.num_pages
        if page > num_pages or page <= 0:
            page = 1
        # 获取当前页的Page实例对象
        order_page = paginator.page(page)
        print('总页数：', num_pages, '当前页：', order_page.number)

        if num_pages < 5:
            pages = range(1, num_pages + 1)
        elif page <= 3:
            pages = range(1, 6)
        elif num_pages - page <= 2:
            pages = range(num_pages - 4, num_pages + 1)
        else:
            pages = range(page - 2, page + 3)

        context = {
            'order_page': order_page,
            'pages': pages,
            'page': 'order',
        }
        print(pages)
        return render(request, 'user/user_center_order.html', context)


# /user/address
class AddressView(LoginRequiredMixin, View):
    """用户中心-地址页"""

    def get(self, request):
        """显示"""
        user = request.user
        address = Address.objects.get_default_address(user)
        address_all = Address.objects.get_all_address(user)
        count = len(address_all)
        context = {
            'title': '用户中心-收货地址',
            'page': 'address',
            'address': address,
            'count': count,
            'address_all': address_all,
        }
        return render(request, 'user/user_center_site.html', context)

    def post(self, request):
        """地址添加"""
        receiver = request.POST.get('receiver')
        province = request.POST.get('province', '浙江省')
        city = request.POST.get('city', '绍兴市')
        area = request.POST.get('area', '诸暨市')
        print(province, city, area)
        addr = request.POST.get('addr')
        zip_code = request.POST.get('zip_code')
        phone = request.POST.get('phone')
        user = request.user
        address = Address.objects.get_default_address(user)
        if address:
            is_default = False
        else:
            is_default = True

        # 数据校验
        if not all([receiver, addr, phone]):
            return JsonResponse({'message': '数据不完整'})

        # 校验手机号
        if not re.match(r'^1([3-8][0-9]|5[189]|8[6789])[0-9]{8}$', phone):
            return JsonResponse({'message': '手机号格式不合法'})
        phone = int(phone)
        if zip_code == '':
            zip_code = None
        if zip_code:
            try:
                zip_code = int(zip_code)
            except:
                return JsonResponse({'message': '邮编格式不合法'})
        # 添加
        Address.objects.create(user=user,
                               receiver=receiver,
                               province=province,
                               city=city,
                               area=area,
                               addr=addr,
                               zip_code=zip_code,
                               phone=phone,
                               is_default=is_default)

        # 返回应答
        return JsonResponse({'message': 'success'})
        # return redirect(reverse('user:address'))  # get的请求方式

    @method_decorator(csrf_exempt)
    def put(self, request):
        """修改地址"""
        querydict = QueryDict(request.body)
        id = int(querydict.get('id'))
        receiver = querydict.get('receiver')
        province = querydict.get('province', '浙江省')

templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}雷顿商城-登录{% endblock title %}
{% block topfiles%}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/login.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}

{% block body %}

    <div class="login_form_bg">
        <div class="login_top clearfix">
            <a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static 'images/logo.png' %}" alt="图片加载中"></a>
        </div>
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"><img src="{% static 'images/login_banner.png' %}" alt=""></div>
            <div class="slogan fl">闪电配送 · 品质保证</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="{% url 'user:register' %}">立即注册</a>
                </div>
                <div class="form_input">
                    {# 页面的form不设置action, 提交表单时是访问浏览器地址栏中的地址 #}
                    <form method="post">
                        {% csrf_token %}
                        <input type="text" name="username" class="name_input" value="{{ username }}"
                               placeholder="请输入用户名或邮箱">
                        <div id="name_err" class="user_error">
                            <label  style="color: lightpink;">用户名不能为空</label>
                        </div>
                        <input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
                        <div id="pwd_err" class="pwd_error">
                            <label  style="color: lightpink;">密码不能为空</label>
                        </div>
                        <div class="more_input clearfix">
                            <input type="checkbox" name="remember" {{ checked }}>
                            <label>记住用户名</label>
                            <a href="{% url 'user:password_reset' %}">忘记密码</a>
                        </div>
                        <input type="submit" name="" value="登录" class="input_submit">
                    </form>
                </div>
                <div ><span class="error_tip">{{ errmsg }}</span></div>
            </div>
        </div>
    </div>

{% endblock body %}

templates/user/password_change_done.html
{% extends "base.html" %}
{% block topfiles %}
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
{% endblock topfiles %}
{% block title %}密码修改完成{% endblock %}
{% block body %}
<div class="text-center">
    密码修改完成，点击返回<a href="{% url 'user:login' %}">登陆页面</a>
</div>
{% endblock %}

templates/user/password_change_form.html
{% extends "base_user_center.html" %}
{% block topfiles %}
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
{% endblock topfiles %}
{% block title %}密码修改{% endblock %}
{% block body %}
<div class="row text-center">
<div>
<h1>密码修改</h1>
    {% if form.new_password1.help_text %}
    <p class="text-center">{{ form.new_password1.help_text|safe }}</p>
    {% endif %}
</div>

<form action="." method="post" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="old-password">旧密码：</label>
        {{ form.old_password }}
    </div>
    <div class="form-group">
        <label for="new-password1">新密码：</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-group">
        <label for="new-password2">确认密码：</label>
        {{ form.new_password2 }}
    </div>
    <input type="submit" value="提交" class="btn btn-lg btn-primary "/>
</form>
</div>
{% endblock %}

templates/user/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>重置密码</title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
</head>
<body>
    <div class="row text-center vertical-middle-sm">
    <h1>重置密码</h1>
    <p class="text-center">密码已重置，点击返回<a href="{% url 'user:login'%}">登录页面</a></p>
</div>
</body>
</html>

templates/user/password_reset_confirm.html
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
<div class="row text-center vertical-middle-sm">
    <h1>重置密码</h1>
    <p>请输入两次密码，让我们确定它是正确的。</p>
    <form class="form-horizontal" action="." method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="col-md-5 control-label text-right">新密码</label>
            <div class="col-md-6 text-left">{{ form.new_password1 }}</div>
        </div>
        <div class="form-group">
            <label class="col-md-5 control-label text-right">确认密码</label>
            <div class="col-md-6 text-left">{{ form.new_password2 }}</div>
        </div>
        <input type="submit" value="修改密码" class="btn btn-primary btn-lg">
    </form>
</div>

templates/user/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>重置密码</title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
</head>
<body>
<div class="row text-center vertical-middle-sm">
    <h1>重置密码</h1>
    <p>我们已经通过电子邮件将设置密码的说明发送给您，如果您输入的电子邮件地址存在一个帐户，您很快就会收到。</p>
    <p>如果您没有收到电子邮件，请确保您输入了注册时使用的地址，并检查了您的垃圾邮件文件夹</p>
</div>

</body>
</html>

templates/user/password_reset_email.html
{{ user.username }},你好，你之所以收到这封邮件，是因为你正在进行重置密码操作，
重置密码点击{{ protocol }}://{{ domain }}{% url "user:password_reset_confirm" uidb64=uid token=token %}

templates/user/password_reset_form.html
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
<div class="row text-center vertical-middle-sm">
    <h1>忘记密码？重置密码！</h1>
    <p>输入你的邮箱</p>
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="form-group">
            <label class="col-md-5 control-label text-right">邮箱：</label>
            <div class="col-md-6 text-left">{{ form.email }}</div>
        </div>
        <input type="submit" value="发送邮件" class="btn btn-primary btn-lg">
    </form>
</div>

templates/user/user_center_info.html
{% extends 'base_user_center.html' %}
{% block  right_content %}
    <div class="right_content clearfix">
        <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                <li><span>用户名：</span>{{ user.username }}</li>
                {% if address %}
                    <li><span>联系方式：</span>{{ address.phone }}</li>
                    <li><span>联系地址：</span>{{ address.province }}
                        {{ address.city }} {{ address.area }} {{ address.addr }}</li>
                {% else %}
                    <li><span>联系方式：</span>无</li>
                    <li><span>联系地址：</span>无</li>
                {% endif %}
                <li><a href="{% url 'user:password_change' %}" title="点击修改密码">修改密码</a></li>
            </ul>

        </div>

        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                {% for goods in goods_list %}
                    <li>
                        <a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ goods.price }}</span>
                            <span class="unit">{{ goods.price }}/{{ goods.unite }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% empty %}
                    无历史浏览记录
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock right_content %}

templates/user/user_center_order.html
{% extends 'base_user_center.html' %}
{% load static %}
{% block right_content %}
    <div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>
        {% for order in order_page %}
            {% csrf_token %}
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.create_time }}</li>
                <li class="col02">订单号：{{ order.order_id }}</li>
                <li class="col02 stress">{{ order.status_name }}</li>
            </ul>
            <table class="order_list_table w980">
                <tbody>
                <tr>
                    <td width="50%">
                        {% for good in order.order_goods %}
                            <ul class="order_goods_list clearfix">
                                <li class="col01"><a href="{% url 'goods:detail' good.sku.id%}" ><img src="{{ good.sku.image.url }}"></a></li>
                                <li class="col02">{{ good.sku.name }}<em>{{ good.price }}元/{{ good.sku.unite }}</em></li>
                                <li class="col03">{{ good.count }}</li>
                                <li class="col04">{{ good.amount }}元</li>
                            </ul>
                        {% endfor %}
                    </td>
                    <td width="20%">{{ order.total_price|add:order.total_freight }}(含运费:{{ order.total_freight }})元</td>
                    <td width="15%">{{ order.status_name }}</td>
                    <td width="15%"><a href="#" order_id="{{ order.order_id }}" status="{{ order.order_status }}"class="oper_btn">去付款</a></td>
                </tr>
                </tbody>
            </table>
        {% endfor %}
        <div class="pagenation">
            {% if order_page.has_previous %}
                <a href="{% url 'user:order' order_page.previous_page_number %}"> < 上一页 </a>
            {% endif %}
            {% for index in pages %}
                {% if index == order_page.number %}
                    <a href="{% url 'user:order' index %}" class="active">{{ index }}</a>
                {% else %}
                    <a href="{% url 'user:order' index %}">{{ index }}</a>
                {% endif %}
            {% endfor %}
            {% if order_page.has_next %}
                <a href="{% url 'user:order' order_page.next_page_number %}"> 下一页 > </a>
            {% endif %}
        </div>
    </div>
{% endblock right_content %}

{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        $('.oper_btn').each(function () {
            // 获取status
            var status = $(this).attr('status')
            if (status == 1){
                $(this).text('去支付')
            }
            else if (status == 4){
                $(this).text('去评价')
            }
            else if (status == 5){
                $(this).text('已完成')
            }
        })


        $('.oper_btn').click(function () {
            // 获取status
            var status = $(this).attr('status')
            // 获取订单id
            order_id = $(this).attr('order_id')
            if (status == 1){
                // 进行支付
                csrf = $('input[name="csrfmiddlewaretoken"]').val()
                params = {'order_id': order_id, 'csrfmiddlewaretoken': csrf}
                $.post('{% url 'order:pay' %}', params, function (data) {
                    if (data.res == 3){
                        // 引导用户到支付页面
                        window.open(data.pay_url)
                        $.post('{% url 'order:check' %}', params, function () {
                            if (data.res == 3){
                                alert('支付成功')
                                location.reload()
                            } else{
                                alert(data.errmsg)
                            }
                        })
                    } else{
                        alert(data.errmsg)
                    }
                })
            }
            else if (status == 4){
                //其他情况
                // 跳转到评价页面
                location.href = "/order/comment/" + order_id
            }
        })
    </script>
{% endblock bottomfiles %}